---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autopull
  labels:
    app: autopull
{{ include "common.labels" . | indent 4 }}
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: autopull
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: autopull
        ver: 0.0.16
    spec:
      containers:
      - name: autopull
        env:
        - name: AWS_REGION
          value: 'eu-central-1'
        image: atolia/alpine-kubectl-awscli-docker
        imagePullPolicy: Always
        volumeMounts:
        - name: sh
          mountPath: /autopull.sh
          subPath: autopull.sh
        resources:
          limits:
            memory: 512Mi
        command:
        - /bin/sh
        # - -x
        - /autopull.sh
      volumes:
      - name: sh
        configMap:
          name: {{ .Release.Name }}-configmap
